namespace NForza.Wolverine.ValueTypes.Generators.CodeGeneration;

internal static class MartenExtensionTemplates
{
    private const string Template = @"#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using JasperFx.Events;
using Marten;
using Marten.Events;
using NForza.Wolverine.ValueTypes;

namespace Marten;

/// <summary>
/// Extension methods that allow IGuidValueType instances to be used directly
/// with Marten event store and document session APIs without explicit casts.
/// Generated by NForza.Wolverine.ValueTypes.
/// </summary>
public static class MartenGuidValueTypeExtensions
{
    // IEventStoreOperations extensions (session.Events on IDocumentSession)

    public static Task<IEventStream<T>> FetchForWriting<T>(
        this IEventStoreOperations store, IGuidValueType id, CancellationToken cancellation = default) where T : class
        => store.FetchForWriting<T>(id.Value, cancellation);

    public static Task<IEventStream<T>> FetchForWriting<T>(
        this IEventStoreOperations store, IGuidValueType id, long expectedVersion, CancellationToken cancellation = default) where T : class
        => store.FetchForWriting<T>(id.Value, expectedVersion, cancellation);

    public static Task<IEventStream<T>> FetchForExclusiveWriting<T>(
        this IEventStoreOperations store, IGuidValueType id, CancellationToken cancellation = default) where T : class
        => store.FetchForExclusiveWriting<T>(id.Value, cancellation);

    public static ValueTask<T?> FetchLatest<T>(
        this IEventStoreOperations store, IGuidValueType id, CancellationToken cancellation = default) where T : class
        => store.FetchLatest<T>(id.Value, cancellation);

    public static StreamAction StartStream<TAggregate>(
        this IEventOperations store, IGuidValueType id, params object[] events) where TAggregate : class
        => store.StartStream<TAggregate>(id.Value, events);

    public static void ArchiveStream(this IEventStoreOperations store, IGuidValueType id)
        => store.ArchiveStream(id.Value);

    // IQueryEventStore extensions (session.Events on IQuerySession)

    public static Task<T?> AggregateStreamAsync<T>(
        this IQueryEventStore store, IGuidValueType streamId,
        long version = 0, DateTimeOffset? timestamp = null, T? state = default, long fromVersion = 0,
        CancellationToken token = default) where T : class
        => store.AggregateStreamAsync<T>(streamId.Value, version, timestamp, state, fromVersion, token);

    public static Task<IReadOnlyList<IEvent>> FetchStreamAsync(
        this IQueryEventStore store, IGuidValueType streamId,
        long version = 0, DateTimeOffset? timestamp = null, long fromVersion = 0,
        CancellationToken token = default)
        => store.FetchStreamAsync(streamId.Value, version, timestamp, fromVersion, token);

    public static Task<StreamState?> FetchStreamStateAsync(
        this IQueryEventStore store, IGuidValueType streamId, CancellationToken token = default)
        => store.FetchStreamStateAsync(streamId.Value, token);
}";

    public static string Generate()
    {
        return Template;
    }
}
